import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/common/navbar";
import { Toaster } from "@/components/ui/sonner"
import AuthProvider from "@/Services/providers/auth-provider";
import Footer from "@/components/common/footer";
import CartContextProvider from "@/Services/providers/cart-provider";
import HappyCustomers from "@/components/common/Reviews";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CartContextProvider>
            <>
              <NavBar />
              {children}
              <Toaster position={"top-right"} richColors />
              <HappyCustomers />

              <Footer />
            </>
          </CartContextProvider>

        </AuthProvider>
      </body>
    </html>
  );
}
